services:
  test-cliente:
    container_name: test-cliente
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7090:7090"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=7090